### ISSUE TITLE
Running in mocha

### ISSUE THREAD

**Issue by rpelizzi** [trello-archive/node-coffee-backtrace#2]
Any idea how to get this to run in a test runner like mocha?
using `mocha -r coffee-backtrace` and importing it into the test files doesn't seem to work.

**Comment by dpatti** [comment]
I gave it a decent rewrite using a much more stable method. Try out version 0.2.0, it works for me with `-r coffee-backtrace`, although it does lose the gray coloring in the process.

**Comment by rpelizzi** [comment]
the stack trace shows context and line numbers from the compiled JavaScript files, not the coffeescript file. Is this the intended behavior?

**Comment by dpatti** [comment]
Right now, yes. I plan on adding support for coffee versions that have sourcemapping enabled in the near future though.
